### ISSUE TITLE
Add support for URL's without protocol and mailto:'s

### ISSUE THREAD

**Issue by marciodsousa** [visualjerk/quill-magic-url#1]
Hi,

Could you also allow URL's without protocol (like www.google.com instead of http://www.google.com) and mailto's (mailto:marcio@email.com)?

Or perhaps allow a config option that would accept regex to test?

Cheers,
Marcio

**Comment by marciodsousa** [comment]
if https://github.com/visualjerk/quill-magic-url/pull/2 is merged, that this could be achieved by:

```
const quill = new Quill(editor, {
  modules: {
      magicUrl: {
        globalRegularExpression: /(https?:\/\/|www\.|mailto:)[\S]+/g,
        urlRegularExpression: /(https?:\/\/[\S]+)|(www.[\S]+)|(mailto:[\S]+)/
      }
  }
});
```

**Comment by visualjerk** [comment]
Hi @marciodsousa,

thanks for your contribution. I like the idea of providing the option for an own regex.

Cheers
