### ISSUE TITLE
Why is "babel-loader" not a dev dependency?

### ISSUE THREAD

**Issue by andrucz** [visualjerk/quill-magic-url#12]
First of all, thanks for this great Quill module.

Is there a reason to add `babel-loader` as a dependency instead of a dev dependency? It causes some issues when adding this module to a project that depends on another version of `babel-loader`.

**Comment by vfonic** [comment]
+1

I'm using `"@babel/core": "^7.5.5",` and, in order to use this plugin as-is, I'd need to add another version of `babel-core`.

Is there any fork that fixes this for the time being?

**Comment by vfonic** [comment]
I've created a fork that works with babel 7. It's just a hack/temporary solution and is not meant to be used long term.

https://github.com/vfonic/quill-magic-url

**Comment by ankon** [comment]
@vfonic will you open a PR for your changes?

**Comment by vfonic** [comment]
My solution was kind-of-a-hack / quickfix. I don't know if this package is still maintained. @visualjerk are you accepting PRs?

Thanks!

**Comment by visualjerk** [comment]
Yes, I still accept PRs and am grateful for every help.
