### ISSUE TITLE
Feature request: Fix native 'link' functionality

### ISSUE THREAD

**Issue by vfonic** [visualjerk/quill-magic-url#13]
Perhaps this can be used to fix/replace links that get detected to be absolute urls, instead of local path.

For example [check this link](www.example.com)

This is what happens when users use "link" in quill toolbar.

**Comment by jhoughjr** [comment]
the link is not found.

**Comment by vfonic** [comment]
@jhoughjr exactly. That's on purpose to show why this plugin should be used to fix this.

**Comment by visualjerk** [comment]
I guess this functionality should rather be added to the toolbar module of quill. It would be a bit hacky to replace the default behavior of native module by installing a 3rd party module.

It can however be achieved by providing a custom link handler in the toolbar options: https://quilljs.com/docs/modules/toolbar/#handlers
