### ISSUE TITLE
Include ES6 synatx in dist

### ISSUE THREAD

**Issue by qianL93** [visualjerk/quill-magic-url#14]

**Comment by cliftonlabrum** [comment]
I'm trying to import this module in a browser. Is that what your issue refers to? Did you ever figure out how?

**Comment by qianL93** [comment]
> I'm trying to import this module in a browser. Is that what your issue refers to? Did you ever figure out how?

You should check if the code that you imported include some synatx that your browser doesn't support. Or you can translate all your code to compatible code by some tool like babel. 
And about this issue. We mostly build ES5 synatx bundles for browser  environment.

**Comment by visualjerk** [comment]
Currently webpack doesn't support this bundle format, so it would require the use of rollup instead. As this package is pretty small already, I am not sure if the benefits justify the effort. But I am happy to accept PRs for this.
