### ISSUE TITLE
Link preview like social Og tags - 

### ISSUE THREAD

**Issue by santoshprakash** [visualjerk/quill-magic-url#16]
how Can we use this library to show link preview? in side Quill editor? 

<meta property="og:url"                content="some url" />
<meta property="og:type"               content="article" />
<meta property="og:title"              content="Something" />
<meta property="og:description"        content=" creative thinking?" />
<meta property="og:image"              content="some.jpg" />

**Comment by visualjerk** [comment]
I am afraid this is out of scope for this package. You would need some kind of backend service to provide you with the meta data and images needed to display a link preview.
