### ISSUE TITLE
Query parameters reordered when linkified

### ISSUE THREAD

**Issue by julianlam** [visualjerk/quill-magic-url#21]
Hi there -- this is low priority and causes issues with My Specific Implementation:tm: but most likely won't affect anyone else whatsoever.

Regardless...

When a URL is pasted, it seems any query string parameters are parsed and re-ordered into alphabetical order.

The following example string:

```
https://example.org?foobar=true&barbaz=quux

https://example.org?barbaz=quux&foobar=true
```

Will result in both URLs with the anchor `https://example.org?barbaz=quux&foobar=true` even though the text remains as entered.

This only caused issues for me because I have a separate piece of logic that checks for anchors and only does its thing if anchor href and anchor text are an exact match. I'll adjust it so it is less strict, but I thought maybe you might want to know about this behaviour too :smile:

**Comment by visualjerk** [comment]
Thanks for raising awareness to this. It is something that [normalize-url does by default](https://github.com/sindresorhus/normalize-url#sortqueryparameters).

You can remove the automatic sorting by adding this to the configuration:

```
magicUrl: {
  normalizeUrlOptions: {
    sortQueryParameters: false
  }
}
```

**Comment by julianlam** [comment]
Thanks for sharing, passing in the additional option works perfectly :+1:
