### ISSUE TITLE
Feature Request: Detect any links not only starting with https and http

### ISSUE THREAD

**Issue by shyamal890** [visualjerk/quill-magic-url#3]
Currently the plugin only detects and converts links that starts with `https` or `http`.

Consider the following enteries by a user:

- `google.com` -> convert to `https://google.com`
- `www.google.com` -> convert to `https://www.google.com`

**Comment by visualjerk** [comment]
Thanks for your feature request. You can already achieve that by providing custom regular expressions to the module like so:

```javascript
var quill = new Quill('#editor', {
  theme: 'snow',
    modules: {
      magicUrl: {
        globalRegularExpression: /(https?:\/\/|www\.|mailto:)[\S]+/g,
        urlRegularExpression: /(https?:\/\/[\S]+)|(www.[\S]+)|(mailto:[\S]+)/
      }
   }
});
```

This example would make the module detect `mailto:jon@google.com`, `www.google.com`, `http://google.com` and `https://google.com`.

Of course you can extend these expressions to also detect `google.com`.  However it seems to be best practice to not auto-detect these kind of strings.

If you want to deep dive into the realm of crazy url detection regex, give this a read: [https://mathiasbynens.be/demo/url-regex](https://mathiasbynens.be/demo/url-regex)
