### ISSUE TITLE
Feature Request: CDN JS link and demo page

### ISSUE THREAD

**Issue by GokulNC** [visualjerk/quill-magic-url#30]
Can you please upload a static JS file to a CDN like unpkg.com instead of having to use Node?

Also, it would be a lot better to host a page on GitHub Pages for demo.

**Comment by visualjerk** [comment]
unpkg.com automatically hosts all packages found on npm. You can use it like so:

<script src="https://unpkg.com/quill-magic-url@2.0.4/dist/index.js"></script>

I will add a note to the README, so it is easier to find in the future. Will also add a link to the demo page there, when I have the time.
