### ISSUE TITLE
Bug: additional delta operation for newline character

### ISSUE THREAD

**Issue by fschindler** [visualjerk/quill-magic-url#36]
Hi,

version 3.0.0 introduced the following bug:
For any text node containing a newline character an additional delta operation is added.

I've created a unit test for this:
https://github.com/fschindler/quill-magic-url/blob/adb2d775be482330fbf0fc878ab8f176cbba83ea/src/index.test.js#L37

For 9bffda9fe8b993d85928ee85bc595b568ef2204c this test fails:
```
    - Expected  - 1
    + Received  + 6

      Object {
    -   "ops": Array [],
    +   "ops": Array [
    +     Object {
    +       "insert": "
    + ",
    +     },
    +   ],
      }
```

For e8f7919e7c1ad0c96bfcde5791c8b166974a88e4 the test passes.

**Comment by heiCode** [comment]
God catch and fix!
