### ISSUE TITLE
Is it possible to set url via .com .tech and so on?

### ISSUE THREAD

**Issue by bardobrado** [visualjerk/quill-magic-url#38]
I was looking to make a hyperlink without using https or www, but with .com. How to do that?

Thanks in advance.

**Comment by visualjerk** [comment]
You can adjust the module options for `urlRegularExpression`, `globalRegularExpression` and `normalizeRegularExpression` to your needs.

Example in your quill config:

```js
...
modules: {
  magicUrl: {
    globalRegularExpression: /(https?:\/\/|www\.)[\w-\.]+\.[\w-\.]+(\/([\S]+)?)?|([\S]+(.com|.tech)(\/[\S]+)?)/gi,
    urlRegularExpression: /(https?:\/\/|www\.)[\w-\.]+\.[\w-\.]+(\/([\S]+)?)?|([\S]+(.com|.tech)(\/[\S]+)?)/i,
    normalizeRegularExpression: /(https?:\/\/|www\.)[\S]+|([\S]+(.com|.tech)(\/[\S]+)?)/i,
  },
},
...
```

Inside the part with `.com|.tech` you can add any top level domain, separated by `|`.
