### ISSUE TITLE
Magic URL doesn't break if the text is no longer a valid url while typing

### ISSUE THREAD

**Issue by FitTech961** [visualjerk/quill-magic-url#40]
I'll show an example here of the Quill magic URL demo: 

https://user-images.githubusercontent.com/74727995/111616867-0ff96900-87eb-11eb-9e74-ac9a913985f2.mov

As you can see in the example above as the typed URL is no longer a valid URL, it's still linked. Also when you remove a link but the text is still valid it will auto link again. Any idea on how to fix this?

**Comment by visualjerk** [comment]
The first point is actually working as expected. Once a text has been marked as a link, the link should not be automatically removed or altered by this plugin. Imagine editing a text, that has links on phrases like "see details" or "click here". Changing these should not result in breaking or altering the existing link.

The second point is indeed a bug that might be a bit tricky to fix. Any contribution is appreciated :)

**Comment by visualjerk** [comment]
This has been fixed in version 4.0.0
