### ISSUE TITLE
Typing in a URL but not hitting enter, tab or spacebar does not detect link properly

### ISSUE THREAD

**Issue by jskitz** [visualjerk/quill-magic-url#48]
I'm not sure that this is going to be easy to fix, but my Quill Editor autosaves on blur, and I noticed that if I type in something that ends in a URL like the following (note there are no characters at the end of the link and this was typed in and not pasted):

`Please follow this link: https://www.example.com`

and either click save or just blur away from the editor, it will not detect that as a link unless I hit enter, tab or spacebar after the link before. Seems the link detection requires whitespace after the link to run the auto link detection.

This is a pretty minor issue, but just thought I would raise it anyway since there are workflows that may not end links with whitespace.

Thanks for putting this tool together. Much appreciated.

**Comment by ganesh-500** [comment]
For me also have same functionality can some assit on this

**Comment by visualjerk** [comment]
Sounds like a helpful feature. Any help with implementing this is greatly appreciated.

**Comment by pikachunakapika** [comment]
I just did:
``registerBlurListener() {
    this.quill.root.addEventListener('blur', () => {
      this.checkTextForUrl();
    }); 
  }```
And add ```this.registerBlurListener()``` after ```this.registerPasteListener()```

**Comment by nate-knight** [comment]
I don't think this is fixed. Wasn't the request to auto-recognize URLs without having to blur on the text? Currently, I have to add a space afterward before it will turn the text into a link.

**Comment by visualjerk** [comment]
The request was to recognize an URL when typing it without adding whitespace at the end and clicking / tabbing outside of the editor. With the current version this seems to work just fine.

**Comment by nate-knight** [comment]
> The request was to recognize a URL when typing it without adding whitespace at the end and clicking / tabbing outside of the editor. With the current version this seems to work just fine.

I am not experiencing that behavior locally or on your demo site: https://visualjerk.github.io/quill-magic-url/ . I have to add a space after the text before it will make it a URL. Is the version on your demo site the latest?

**Comment by visualjerk** [comment]
Just to make sure, we are on the same page. The behavior can be tested by the following steps:

1. Open https://visualjerk.github.io/quill-magic-url/
1. Click inside the editor
1. Type "https://test.com"
1. Click outside of the editor
1. The text "https://test.com" should now have been converted to a link

Is that the same behavior, you would expect, or would you expect the link conversion without step 4?

**Comment by nate-knight** [comment]
Thanks for the follow-up. I now see that the editor performs the check when blurred. I think that is fine. It seems that some editors (eg. Mac Notes, Evernote) perform auto-link conversions only after a space is entered. Others, such as Slack, perform the conversion as soon as a valid url is typed, without a space at the end. It could be helpful to have an optional parameter give the consumer the option to perform the check on every input change.

**Comment by visualjerk** [comment]
Indeed, that sounds like a helpful option. Would you mind creating a separate feature request for that?
