### ISSUE TITLE
URL may contain a port

### ISSUE THREAD

**Issue by v1talii-dev** [visualjerk/quill-magic-url#59]
URL may contain a port. It is not highlighted in the editor when inserted. How can I solve this problem?

Steps to reproduce:
- open [demo page](https://visualjerk.github.io/quill-magic-url/)
- insert the link http://192.168.0.0:8080 (ctrl+shift+v)

**Comment by iLodeStar** [comment]
How about using a custom regex to qualify port as part of valid URL.

Here's the regex that I wrote for my use case (have added a few tests for same).

[regexr.com/62ijf](regexr.com/62ijf)

 you can add custom regular expression to your quill config, as follows: 


```
modules: {
  magicUrl: {
globalRegularExpression:
    /(?:(?:(?:https?|ftp):)?\/\/)?(?:\S+(?::\S*)?@)?(?:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d?|[1-9]?)(?:\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d?|\d?)){3}|(?:(?:[a-z0-9\u00a1-\uffff][a-z0-9\u00a1-\uffff_-]{0,62})?[a-z0-9\u00a1-\uffff]\.)+(?:[a-z\u00a1-\uffff]{2,}\.?))(?::\d{2,5})?(?:[/?#]\S*)?/gi,
  urlRegularExpression:
    /(?:(?:(?:https?|ftp):)?\/\/)?(?:\S+(?::\S*)?@)?(?:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d?|[1-9]?)(?:\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d?|\d?)){3}|(?:(?:[a-z0-9\u00a1-\uffff][a-z0-9\u00a1-\uffff_-]{0,62})?[a-z0-9\u00a1-\uffff]\.)+(?:[a-z\u00a1-\uffff]{2,}\.?))(?::\d{2,5})?(?:[/?#]\S*)?/,
  },
},
```

Hope it helps.

**Comment by v1talii-dev** [comment]
@iLodeStar thx. i have implemented something similar in my project, it works.
