### ISSUE TITLE
Incorrect link display in the standard link management editor

### ISSUE THREAD

**Issue by v1talii-dev** [visualjerk/quill-magic-url#60]
This is due to the work of the plugin [vue-quill-editor](https://github.com/surmon-china/vue-quill-editor/blob/master/src/editor.vue#L163), which sets the default values through the method `pasteHTML`.

Steps to reproduce:
1. Paste the existing HTML into the editor, for example: `<a href="https://yandex.com">https://google.com</a>`
2. Click on the link https://google.com
3. In the link editing menu that appears, the text https://google.com will be displayed, instead of the text https://yandex.com

[Example to reproduce on codepen](https://codepen.io/iron_vd/pen/YzVjLjE?editors=0010)
![image](https://user-images.githubusercontent.com/12966923/128031004-9fb104ff-ef45-4c1e-8bfc-00d1d55a8110.png)

**Comment by v1talii-dev** [comment]
@visualjerk please can comment on this situation?

**Comment by visualjerk** [comment]
A fix for this is released in version 4.1.3
