### ISSUE TITLE
Unexpected triggering of URLs on blur

### ISSUE THREAD

**Issue by ajalexander** [visualjerk/quill-magic-url#65]
There is some behavior that seems unexpected that triggers on blur.

### Unexpected cases

There are two cases that seem off from my expectations:

#### Removing a link and changing focus

- Enter the Quill editor
- Enter text `https://www.google.com test`
- Click to move the cursor to be between the `o` and the `m` in `.com`
- Use the pop-up to remove the link
- Click out of the editor
- **Expected:** All text will be plain text
- **Actual:** There is a URL for `https://www.google.co` with the `m` from `.com` left as plain text

#### Clicking into URL-like text and changing focus

- Enter the Quill editor
- Enter text `https://www.google.com test`
- Click to move the cursor to be between the `o` and the `m` in `.com`
- Use the pop-up to remove the link
- Click to the end of the text
- Click out of the editor
- (_Note:_ At this time `https://www.google.com test` will all be present as plain text)
- Click to move the cursor to be between the `o` and the `m` in `.com`
- Use the pop-up to remove the link
- Click out of the editor
- **Expected:** All text will be plain text
- **Actual:** There is a URL for `https://www.google.co` with the `m` from `.com` left as plain text

**Comment by ajalexander** [comment]
To more narrowly cover the needs of #48 (which prompted #56), I'm wondering when running on blur the URL matching should only occur if the cursor is at the end of the text area or if it is immediately followed by a space.

**Comment by visualjerk** [comment]
Thanks for submitting this bug. It should be fixed in the newest release:
https://github.com/visualjerk/quill-magic-url/releases/tag/4.1.4
