### ISSUE TITLE
Empty anchor tags causes a crash

### ISSUE THREAD

**Issue by martinoman** [visualjerk/quill-magic-url#76]
Hello! Great project!

I found that magic url crashes when trying to parse empty anchor tags. This happened when we provided a quill field with some initial value. The smallest input I found to recreate this was `<a href="http://www.google.com/"></a>`.

**Comment by visualjerk** [comment]
Thanks for submitting this issue. It will be fixed in [version 4.1.5](https://github.com/visualjerk/quill-magic-url/releases/tag/4.1.5).
