### ISSUE TITLE
URLs break if you edit them

### ISSUE THREAD

**Issue by msmsmsmsms** [visualjerk/quill-magic-url#8]
Once magic-url recognized the URLs, you cannot edit them or they break.  
For example, adding a space in the middle of _www.github.com_ turns it into one URL looking _www.git_ linking to _http://www.git_ and one URL looking like _hub.com_ linking to _http://www.github.com_.  
Additionally, if you start typing in a recognized URL, the text content changes, but the href stays the same. If you change _www.github.com_ to _www.foobar.com_ the href is still _www.github.com_. 

Expected result would be, that the href mirrors the visible URL.

**Comment by visualjerk** [comment]
@msmsmsmsms The purpose of this module is to automatically add links after the user typed or pasted a valid URL. After this point everything else should be handled by Quill. Quill - like most WYSIWYGs - does not synchronize the text and href of a link tag. That totally makes sense, as the text and href could be something completely different.

That said, there was still an issue with adding spaces inside the text of a link. Thank you for pointing that out and thanks @n1ghtmare for the fix.
