### ISSUE TITLE
Not working with React-Quill

### ISSUE THREAD

**Issue by nesh325** [visualjerk/quill-magic-url#82]
Trying to use this with React-quill but does not seem to work. 
I've imported and registered it to the quill instance and set to true in modules. 

I get this warning message sometimes in my console related to it 
![Screen Shot 2022-07-26 at 16 17 17 PM](https://user-images.githubusercontent.com/70300148/181104708-769c9b37-f8a4-4fcf-a131-73f36d25bb15.png)

Any way to get this working with React-quill?

**Comment by visualjerk** [comment]
Hi! Can you provide a minimal reproduction of this issue on https://stackblitz.com? That would make debugging a lot easier.

**Comment by visualjerk** [comment]
Closing this for now, as we are missing a reproduction example.

**Comment by Shubhra1028** [comment]
@nesh325, FYI, I get this message in development mode, when I make some changes in the react-quill modules.

for example, I toggled the mailRegularExpression below.
![image](https://user-images.githubusercontent.com/31990673/187172771-6035e2e2-a299-46a3-9589-65a1f9e5cfe6.png)
